version: '3'

services:
  traefik:
    image: traefik:1.6.2
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    labels:
      - traefik.backend=monitor
      - traefik.frontend.rule=Host:monitor.mystic.home
      - traefik.port=8080
      - traefik.docker.network=proxy
      - traefik.enable=true
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/external_one/docker/traefik/traefik.toml:/traefik.toml
      - /mnt/external_one/docker/traefik/certs/:/certs/

  nginx:
    image: nginx:1.14-alpine
    container_name: nginx
    labels:
      - traefik.backend=home
      - traefik.frontend.rule=Host:mystic.home
      - traefik.port=80
      - traefik.docker.network=proxy
      - traefik.enable=true
    expose:
      - "80"
    networks:
      - proxy
    volumes:
      - /mnt/external_one/docker/nginx/html/:/usr/share/nginx/html/
      - /mnt/external_one/docker/nginx/nginx.conf:/etc/nginx/conf.d/mystic_nginx.conf
      - /mnt/external_one/docker/nginx/.htpasswd:/etc/nginx/.htpasswd

  nextcloud:
    image: nextcloud:13.0.2
    container_name: nextcloud
    depends_on:
      - postgres_one
    labels:
      - traefik.backend=cloud
      - traefik.frontend.rule=Host:cloud.mystic.home
      - traefik.port=80
      - traefik.docker.network=proxy
      - traefik.enable=true
    expose:
      - "80"
    networks:
      - proxy
      - internal
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - POSTGRES_DB=mystic
      - POSTGRES_USER=mystic
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres_one
    volumes:
      - /mnt/external_one/docker/nextcloud:/var/www/html
      - /mnt/external_one/docker/nextcloud/apps:/var/www/html/custom_apps
      - /mnt/external_one/docker/nextcloud/config:/var/www/html/config
      - /mnt/external_one/docker/nextcloud/data:/var/www/html/data
      - /mnt/external_one/docker/nextcloud/themes:/var/www/html/themes

  wordpress:
    image: wordpress:4.9.6
    container_name: wordpress
    depends_on:
      - mysql_one
    labels:
      - traefik.backend=blog
      - traefik.frontend.rule=Host:blog.mystic.home
      - traefik.port=80
      - traefik.docker.network=proxy
      - traefik.enable=true
    environment:
      - WORDPRESS_DB_HOST=mysql_one
      - WORDPRESS_DB_USER=mystic
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=mystic
    expose:
      - "80"
    networks:
      - proxy
      - internal
    volumes:
      - /mnt/external_one/docker/wordpress:/var/www/html

  postgres_one:
    image: postgres:10.4-alpine
    container_name: postgres_one
    environment:
      - POSTGRES_USER=mystic
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mystic
    expose:
      - "5432"
    networks:
      - internal
    volumes:
      - /mnt/external_one/docker/pg_db_one:/var/lib/postgresql/data

  mysql_one:
    image: hypriot/rpi-mysql:5.5
    container_name: mysql_one
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mystic
      - MYSQL_USER=mystic
      - MYSQL_PASSWORD=password
    expose:
      - "3306"
    networks:
      - internal
    volumes:
      - /mnt/external_one/docker/mysql_db_one:/var/lib/mysql

networks:
  proxy:
    external: true
  internal:
    external: false
